version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - ah_datahub_szapi_DB__uri=postgresql://postgres:postgres@db:5432/ah_datahub_szapi
      - ah_datahub_szapi_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: ah_datahub_szapi_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/ah_datahub_szapi_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=ah_datahub_szapi, ah_datahub_szapi_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
